### ISSUE TITLE
[Question]: Support for Sentry 7

### ISSUE THREAD

**Issue by abelfernandezh** [wix/sentry-testkit#108]
Hey, I´m having problems testing the latest release of Sentry. Does this library support Sentry 7?

**Comment by mlmmn** [comment]
@abelfernandezh I've just prepared a PR with support for v7 https://github.com/wix/sentry-testkit/pull/109

Dunno who to ping to review though 🤔

**Comment by Joroze** [comment]
Would be great to have this released!
