### ISSUE TITLE
[Question]: Support for @sentry/react-native v4

### ISSUE THREAD

**Issue by Yupeng-li** [wix/sentry-testkit#110]
Hi, 

I use this library to test sentry in a react-native project, but I start having issues after upgrading `@sentry/react-native` from v3 to v4. Apparently `@sentry/react-native` v4 is using `sentry-javascript` v7+ which has breaking changes that haven't been dealt with in this library. Is there a plan to support `@sentry/react-native` v4 and `sentry-javascript` v7?  

Many thanks

**Comment by liamjones** [comment]
Related issue for supporting sentry-javascript v7: https://github.com/wix/sentry-testkit/issues/108 and PR to support it: https://github.com/wix/sentry-testkit/issues/108

**Comment by zivl** [comment]
hey @Yupeng-li 
see tracking of this issue in #https://github.com/wix/sentry-testkit/issues/108

**Comment by zivl** [comment]
released `sentry-testkit@4.0.1`

**Comment by liamjones** [comment]
FYI still seems to be broken with RN atm: https://github.com/wix/sentry-testkit/issues/113
