### ISSUE TITLE
Deployment failing in @sentry/utils/esm

### ISSUE THREAD

**Issue by kevandrada** [wix/sentry-testkit#48]
WARNING in ./~/@sentry/utils/esm/misc.js
Module not found : error : Can't resolve 'perf_hooks' in '/opt/atlassian/pipelines/agent/build/node_modules/@sentry/utils/esm' [/opt/atlassian/pipelines/agent/build/project.csproj]
       @ ./~/@sentry/utils/esm/misc.js 270:28-45
       @ ./~/@sentry/utils/esm/index.js
       @ ./~/@sentry/browser/esm/index.js
       @ ./ClientApp/app.js
       @ ./ClientApp/boot-app.js

**Comment by zivl** [comment]
hey @kevandrada, sorry for the delay.
is this still relevant? can you specify your `sentry`/`sentry-testkit` versions?
