### ISSUE TITLE
reset() does not reset the breadcrumbs

### ISSUE THREAD

**Issue by rolandoldengarm** [wix/sentry-testkit#60]
When creating exceptions with breadcrumbs in 2 tests, the second test will have the breadcrumbs from the first test.
```
describe('debug', () => {
    beforeEach(() => {
      testkit.reset();
    });
    it('should log a message 1', () => {
      Sentry.addBreadCrumb({message: 'messageText'});
      Sentry.captureException(new Error('test 1'));

      expect(testkit.reports()).toHaveLength(1);
      const report = testkit.reports()[0];

      expect(report.breadcrumbs).toHaveLength(1);
    });

    it('should log a message 2', () => {
      Sentry.addBreadCrumb({message: 'messageText'});
      Sentry.captureException(new Error('test 2'));

      expect(testkit.reports()).toHaveLength(1);
      const report = testkit.reports()[0];

      expect(report.breadcrumbs).toHaveLength(1);
    });
});
```
The second test fails as the breadcrumbs array contains 2 items:
![image](https://user-images.githubusercontent.com/14539000/95120962-d982e100-07aa-11eb-8c62-da0ad0737021.png)

**Comment by zivl** [comment]
can you state your `sentry` and `sentry-testkit` versions?

**Comment by zivl** [comment]
I think it's related to recent changes has been done after moving to `yarn` and refresh the locked versions of some dependencies. will revert back

**Comment by zivl** [comment]
@rolandoldengarm  reverted here https://github.com/wix/sentry-testkit/commit/091bcc0dd3f977e3f13cfb39482b9887955ee0a3
let me know if you still see this bug
