### ISSUE TITLE
Question: can you use sentry-testkit to extract tracing / performance data?

### ISSUE THREAD

**Issue by ianwalter** [wix/sentry-testkit#63]
Not sure if sentry-testkit only provides exception reports or if I just haven't configured Sentry correctly. Seems like the former.
Thank you.

**Comment by zivl** [comment]
can you pls elaborate more?
specify a use case? what performance data? etc...

**Comment by ohana54** [comment]
sentry-testkit indeed provides only exception reports, it doesn't yet support the performance metrics product. I just encountered the same need and will try to work on a PR for that.

**Comment by ohana54** [comment]
@ianwalter I don't know if it's still relevant but I opened https://github.com/wix/sentry-testkit/pull/82

**Comment by ohana54** [comment]
@zivl since the PR was merged and the feature released, can we close this issue?

**Comment by zivl** [comment]
yep!
thanks @ohana54 & @ianwalter
