### ISSUE TITLE
generate automatic CHANGELOG.md file

### ISSUE THREAD

**Issue by zivl** [wix/sentry-testkit#67]
We need to investigate what's the effort to create and generate a `CHANGELOG.md` automatically for every release

**Comment by sidoruk-sv** [comment]
Will grab this)

**Comment by sidoruk-sv** [comment]
@zivl

So does the question for "`CHANGELOG.md` file VS `releases` github page" has already been resolved, or we could discuss that?

For now I mention that some known libraries are migrated to `releases` page only: https://github.com/testing-library/react-testing-library/blob/master/CHANGELOG.md

Don't know is there an ability to support both approaches, will try to dig there.

Or we are ok with one of approaches, which one?)

**Comment by zivl** [comment]
sure!
up until now, i was not using the `tag` and `releases` options of github.
I manually published it.
I've started something to make it automatic upon `tag`, as can be seen in `travis.yml` file, but I've never tagged...
i guess i got used to manually publishing
